CREATE TABLE IF NOT EXISTS nutritions (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    source VARCHAR(255) NOT NULL,
    chunk_id INT NOT NULL,
    text MEDIUMTEXT NOT NULL,
    embedding VECTOR(768) NOT NULL
);

ALTER TABLE nutritions SET TIFLASH REPLICA 1;

CREATE VECTOR INDEX idx_pdf_chunks_embedding
ON nutritions ((VEC_COSINE_DISTANCE(embedding))) USING HNSW;